ALTER TABLE usuario ADD COLUMN IF NOT EXISTS telefone VARCHAR(20);
ALTER TABLE usuario ADD COLUMN IF NOT EXISTS cpf_cnpj VARCHAR(18);
ALTER TABLE usuario ADD COLUMN IF NOT EXISTS data_nascimento DATE;
