-- 1. Tabela de Usuários (Acesso ao Sistema)
CREATE TABLE usuario (
    id_usuario INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    senha_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) DEFAULT 'mecanico',
    ativo BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE
);

-- 2. Tabela de Clientes
CREATE TABLE cliente (
    id_cliente INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    telefone VARCHAR(20),
    email VARCHAR(100),
    cpf_cnpj VARCHAR(18),
    data_nascimento DATE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE
);

-- 3. Endereços (Relacionado a Cliente)
CREATE TABLE endereco (
    id_endereco INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente INT NOT NULL,
    logradouro VARCHAR(150) NOT NULL,
    numero VARCHAR(10),
    cep VARCHAR(9),
    complemento VARCHAR(100),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_endereco_cliente FOREIGN KEY (id_cliente) REFERENCES cliente(id_cliente)
);

-- 4. Marcas de Veículos
CREATE TABLE marca (
    id_marca INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(50) NOT NULL,
    pais_origem VARCHAR(50),
    site_oficial VARCHAR(150),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE
);

-- 5. Modelos de Veículos
CREATE TABLE modelo (
    id_modelo INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_marca INT NOT NULL,
    nome_modelo VARCHAR(50) NOT NULL,
    ano_lancamento INT,
    tipo_combustivel VARCHAR(30),
    categoria VARCHAR(30),
    num_portas INT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_modelo_marca FOREIGN KEY (id_marca) REFERENCES marca(id_marca)
);

-- 6. Veículos
CREATE TABLE veiculo (
    id_veiculo INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    placa VARCHAR(10) UNIQUE NOT NULL,
    ano_fabricacao INT,
    cor VARCHAR(30),
    id_cliente INT NOT NULL,
    id_modelo INT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_veiculo_cliente FOREIGN KEY (id_cliente) REFERENCES cliente(id_cliente),
    CONSTRAINT fk_veiculo_modelo FOREIGN KEY (id_modelo) REFERENCES modelo(id_modelo)
);

-- 7. Mecânicos
CREATE TABLE mecanico (
    id_mecanico INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    especialidade VARCHAR(100),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE
);

-- 8. Serviços Oferecidos
CREATE TABLE servico (
    id_servico INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao TEXT NOT NULL,
    preco DECIMAL(12,2) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE
);

-- 9. Peças em Estoque
CREATE TABLE peca (
    id_peca INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    preco_unitario DECIMAL(12,2) NOT NULL,
    quantidade_estoque INT DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE
);

-- 10. Movimentação de Estoque
CREATE TABLE movimentacao_estoque (
    id_movimentacao INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_peca INT NOT NULL,
    tipo_movimentacao VARCHAR(10) CHECK (tipo_movimentacao IN ('entrada', 'saida')),
    quantidade INT NOT NULL,
    motivo VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_movimentacao_peca FOREIGN KEY (id_peca) REFERENCES peca(id_peca)
);

-- 11. Ordem de Serviço (OS)
CREATE TABLE ordem_servico (
    id_os INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_veiculo INT NOT NULL,
    id_mecanico INT NOT NULL,
    descricao_problema TEXT,
    status VARCHAR(30) DEFAULT 'aberta',
    data_abertura TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    data_conclusao TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_os_veiculo FOREIGN KEY (id_veiculo) REFERENCES veiculo(id_veiculo),
    CONSTRAINT fk_os_mecanico FOREIGN KEY (id_mecanico) REFERENCES mecanico(id_mecanico)
);

-- 12. Relacionamento OS e Serviços (N-para-N)
CREATE TABLE os_servico (
    id_os INT NOT NULL,
    id_servico INT NOT NULL,
    quantidade INT DEFAULT 1,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE,
    PRIMARY KEY (id_os, id_servico),
    CONSTRAINT fk_os_servico_os FOREIGN KEY (id_os) REFERENCES ordem_servico(id_os),
    CONSTRAINT fk_os_servico_serv FOREIGN KEY (id_servico) REFERENCES servico(id_servico)
);

-- 13. Relacionamento OS e Peças (N-para-N)
CREATE TABLE os_peca (
    id_os INT NOT NULL,
    id_peca INT NOT NULL,
    quantidade INT DEFAULT 1,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE,
    PRIMARY KEY (id_os, id_peca),
    CONSTRAINT fk_os_peca_os FOREIGN KEY (id_os) REFERENCES ordem_servico(id_os),
    CONSTRAINT fk_os_peca_peca FOREIGN KEY (id_peca) REFERENCES peca(id_peca)
);

-- 14. Orçamentos
CREATE TABLE orcamento (
    id_orcamento INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente INT NOT NULL,
    id_veiculo INT NOT NULL,
    status VARCHAR(30) DEFAULT 'pendente',
    valor_total DECIMAL(12,2) DEFAULT 0.00,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_orcamento_cliente FOREIGN KEY (id_cliente) REFERENCES cliente(id_cliente),
    CONSTRAINT fk_orcamento_veiculo FOREIGN KEY (id_veiculo) REFERENCES veiculo(id_veiculo)
);

-- 15. Relacionamento Orçamento e Serviços
CREATE TABLE orcamento_servico (
    id_orcamento INT NOT NULL,
    id_servico INT NOT NULL,
    quantidade INT DEFAULT 1,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE,
    PRIMARY KEY (id_orcamento, id_servico),
    CONSTRAINT fk_orc_servico_orc FOREIGN KEY (id_orcamento) REFERENCES orcamento(id_orcamento),
    CONSTRAINT fk_orc_servico_serv FOREIGN KEY (id_servico) REFERENCES servico(id_servico)
);

-- 16. Relacionamento Orçamento e Peças
CREATE TABLE orcamento_peca (
    id_orcamento INT NOT NULL,
    id_peca INT NOT NULL,
    quantidade INT DEFAULT 1,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE,
    PRIMARY KEY (id_orcamento, id_peca),
    CONSTRAINT fk_orc_peca_orc FOREIGN KEY (id_orcamento) REFERENCES orcamento(id_orcamento),
    CONSTRAINT fk_orc_peca_peca FOREIGN KEY (id_peca) REFERENCES peca(id_peca)
);

-- 17. Agendamentos
CREATE TABLE agendamento (
    id_agendamento INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente INT NOT NULL,
    id_veiculo INT NOT NULL,
    data_agendamento TIMESTAMP WITH TIME ZONE NOT NULL,
    descricao TEXT,
    status VARCHAR(30) DEFAULT 'agendado',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_agendamento_cliente FOREIGN KEY (id_cliente) REFERENCES cliente(id_cliente),
    CONSTRAINT fk_agendamento_veiculo FOREIGN KEY (id_veiculo) REFERENCES veiculo(id_veiculo)
);

-- 18. Pagamentos
CREATE TABLE pagamento (
    id_pagamento INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_os INT NOT NULL,
    valor DECIMAL(12,2) NOT NULL,
    forma_pagamento VARCHAR(50),
    status VARCHAR(30) DEFAULT 'pendente',
    data_pagamento TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_pagamento_os FOREIGN KEY (id_os) REFERENCES ordem_servico(id_os)
);

-- 19. Movimentação Financeira
CREATE TABLE movimentacao_financeira (
    id_movimentacao_financeira INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_movimentacao VARCHAR(10) CHECK (tipo_movimentacao IN ('entrada', 'saida')),
    valor DECIMAL(12,2) NOT NULL,
    descricao VARCHAR(255),
    id_pagamento INT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_movimentacao_pagamento FOREIGN KEY (id_pagamento) REFERENCES pagamento(id_pagamento)
);

-- 20. E-commerce: Produtos
CREATE TABLE produto (
    id_produto INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    descricao TEXT,
    preco DECIMAL(12,2) NOT NULL,
    quantidade_estoque INT DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE
);

-- 21. E-commerce: Pedidos
CREATE TABLE pedido (
    id_pedido INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente INT NOT NULL,
    valor_total DECIMAL(12,2) NOT NULL,
    status VARCHAR(30) DEFAULT 'processando',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_pedido_cliente FOREIGN KEY (id_cliente) REFERENCES cliente(id_cliente)
);

-- 22. Relacionamento Pedido e Produtos
CREATE TABLE pedido_produto (
    id_pedido INT NOT NULL,
    id_produto INT NOT NULL,
    quantidade INT DEFAULT 1,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE,
    PRIMARY KEY (id_pedido, id_produto),
    CONSTRAINT fk_ped_prod_pedido FOREIGN KEY (id_pedido) REFERENCES pedido(id_pedido),
    CONSTRAINT fk_ped_prod_produto FOREIGN KEY (id_produto) REFERENCES produto(id_produto)
);